// Generate inside an iOS simulator via scripts/generate-stop-labels.cjs.
// RNSVG's default native typeface is the system font. Bake the four fixed bold
// letters so every road-cache handover avoids CoreText font/locale discovery.
import Foundation
import CoreText
import CoreGraphics

func number(_ value: CGFloat) -> String {
  let formatted = String(format: "%.5f", Double(value))
  return formatted.replacingOccurrences(of: "0+$", with: "", options: .regularExpression)
    .replacingOccurrences(of: "\\.$", with: "", options: .regularExpression)
}

func outline(size: CGFloat) -> String {
  let normal = CTFontCreateUIFontForLanguage(.system, size, nil)!
  let font = CTFontCreateCopyWithSymbolicTraits(normal, size, nil, .traitBold, .traitBold)!
  let attributes = [kCTFontAttributeName: font] as CFDictionary
  let text = CFAttributedStringCreate(nil, "STOP" as CFString, attributes)!
  let line = CTLineCreateWithAttributedString(text)
  let width = CGFloat(CTLineGetTypographicBounds(line, nil, nil, nil))
  var commands = [String]()
  for run in CTLineGetGlyphRuns(line) as! [CTRun] {
    let count = CTRunGetGlyphCount(run)
    var glyphs = [CGGlyph](repeating: 0, count: count)
    var positions = [CGPoint](repeating: .zero, count: count)
    CTRunGetGlyphs(run, CFRange(location: 0, length: count), &glyphs)
    CTRunGetPositions(run, CFRange(location: 0, length: count), &positions)
    for index in 0..<count {
      guard let path = CTFontCreatePathForGlyph(font, glyphs[index], nil) else { continue }
      // SVG's Y axis points down; centre by the same typographic advance as
      // textAnchor="middle", keeping the original baseline supplied by React.
      func point(_ p: CGPoint) -> String {
        "\(number(p.x + positions[index].x - width / 2)) \(number(-p.y - positions[index].y))"
      }
      path.applyWithBlock { raw in
        let element = raw.pointee
        switch element.type {
          case .moveToPoint: commands.append("M \(point(element.points[0]))")
          case .addLineToPoint: commands.append("L \(point(element.points[0]))")
          case .addQuadCurveToPoint: commands.append("Q \(point(element.points[0])) \(point(element.points[1]))")
          case .addCurveToPoint: commands.append("C \(point(element.points[0])) \(point(element.points[1])) \(point(element.points[2]))")
          case .closeSubpath: commands.append("Z")
          @unknown default: fatalError("Unexpected CoreGraphics path element")
        }
      }
    }
  }
  return commands.joined(separator: " ")
}

print("// Generated by scripts/generate-stop-labels.cjs; iOS system-bold STOP at its actual road/sign sizes.")
print("export const STOP_LABEL_PATHS = {")
print("  road: '\(outline(size: 3.4))',")
print("  sign: '\(outline(size: 2.6))',")
print("} as const;")
